import type { CourseManifest, LessonMeta, LocalizedText } from "../types";

/**
 * Generated from this course's `README.md`, which is the human-readable index.
 * When a lesson is added, renamed, or reordered, change it there first, then
 * here, then in `COBERTURA.md` — the app navigates by this list, and the
 * coverage audit has to keep matching it.
 *
 * Titles are Spanish-only for now: the lessons themselves ship in `.es.md` and
 * the app falls back to the default locale for the rest.
 *
 * Lessons marked `kind: "quiz"` have no markdown file — their content lives in
 * `preguntas/` (see `CONTRATO-DE-CLASES.md`, lesson types C and D).
 */

const COURSE_SLUG = "aws-data-engineer-associate";
const COURSE_TITLE: LocalizedText = {
  es: "AWS Certified Data Engineer – Associate (DEA-C01)",
  en: "AWS Certified Data Engineer – Associate (DEA-C01)",
  "pt-BR": "AWS Certified Data Engineer – Associate (DEA-C01)",
};

const MODULES: Record<string, LocalizedText> = {
  "module-0": { es: "Módulo 0 — Preparación y mapa del examen" },
  "module-1": { es: "Módulo 1 — Fundamentos de ingeniería de datos" },
  "module-2": { es: "Módulo 2 — Dominio 1 · Ingesta de datos" },
  "module-3": { es: "Módulo 3 — Dominio 1 · Transformación y procesamiento" },
  "module-4": { es: "Módulo 4 — Dominio 1 · Orquestación y programación" },
  "module-5": { es: "Módulo 5 — Dominio 2 · Elegir y configurar el almacén" },
  "module-6": { es: "Módulo 6 — Dominio 2 · Catálogo, ciclo de vida y modelado" },
  "module-7": { es: "Módulo 7 — Dominio 3 · Automatización y análisis" },
  "module-8": { es: "Módulo 8 — Dominio 3 · Monitoreo, costos y calidad" },
  "module-9": { es: "Módulo 9 — Dominio 4 · Autenticación y autorización" },
  "module-10": { es: "Módulo 10 — Dominio 4 · Cifrado, auditoría y gobierno" },
  "module-11": { es: "Módulo 11 — Repaso final y simulacro" },
};

const LESSONS: LessonMeta[] = [
  { id: "00-01-que-evalua-el-dea-c01", moduleId: "module-0", module: MODULES["module-0"], title: { es: "Qué evalúa el DEA-C01 y qué queda fuera de alcance" } },
  { id: "00-02-como-son-las-preguntas", moduleId: "module-0", module: MODULES["module-0"], title: { es: "Cómo son las preguntas: escenarios, palabras clave y descarte de opciones" } },
  { id: "00-03-plan-de-estudio", moduleId: "module-0", module: MODULES["module-0"], title: { es: "Plan de estudio y cómo usar este curso" } },
  { id: "00-04-inscripcion-y-dia-del-examen", moduleId: "module-0", module: MODULES["module-0"], title: { es: "Inscripción, día del examen y recertificación" } },

  { id: "01-01-que-hace-un-ingeniero-de-datos", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Qué hace un ingeniero de datos y qué es un pipeline de datos" } },
  { id: "01-02-batch-vs-streaming", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Batch, micro-batch y streaming: latencia, volumen y costo" } },
  { id: "01-03-oltp-olap-lake-warehouse", moduleId: "module-1", module: MODULES["module-1"], title: { es: "OLTP, OLAP, data lake, data warehouse y lakehouse" } },
  { id: "01-04-formatos-de-archivo", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Formatos de archivo: CSV, JSON, Avro, Parquet y ORC" } },
  { id: "01-05-particionado-y-compresion", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Particionado, compresión y tamaño de archivo: las tres palancas de costo" } },
  { id: "01-06-esquemas-y-evolucion", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Esquemas: schema-on-read, schema-on-write y evolución" } },
  { id: "01-07-computo-distribuido-y-spark", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Cómputo distribuido y Apache Spark: particiones, shuffle, DAG y ejecutores" } },
  { id: "01-08-mapa-de-servicios", moduleId: "module-1", module: MODULES["module-1"], title: { es: "El mapa de servicios de datos de AWS que entran al examen" } },
  { id: "01-09-comparativas-fundamentos", moduleId: "module-1", module: MODULES["module-1"], title: { es: "★ Tablas comparativas: formatos, latencias y tipos de almacén" } },
  { id: "01-10-analisis-preguntas-modulo-1", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Analiza preguntas de examen: fundamentos" }, kind: "quiz" },

  { id: "02-01-panorama-de-la-ingesta", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Panorama de la ingesta: fuentes, destinos y las decisiones que pregunta el examen" } },
  { id: "02-02-kinesis-data-streams", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Kinesis Data Streams: shards, capacidad, retención y resharding" } },
  { id: "02-03-kinesis-productores-y-consumidores", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Kinesis: productores (KPL, Agent, SDK) y consumidores (KCL, enhanced fan-out)" } },
  { id: "02-04-kinesis-y-lambda", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Kinesis y Lambda: event source mapping, lotes, paralelismo y errores" } },
  { id: "02-05-kinesis-data-firehose", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Kinesis Data Firehose: buffering, dynamic partitioning y conversión de formato" } },
  { id: "02-06-amazon-msk", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Amazon MSK: Kafka gestionado, MSK Serverless y MSK Connect" } },
  { id: "02-07-managed-flink", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Amazon Managed Service for Apache Flink: ventanas y procesamiento de streams" } },
  { id: "02-08-cdc-con-dynamodb-streams", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Change data capture con DynamoDB Streams y Kinesis Data Streams for DynamoDB" } },
  { id: "02-09-aws-dms", moduleId: "module-2", module: MODULES["module-2"], title: { es: "AWS DMS: full load, CDC y validación de la migración" } },
  { id: "02-10-zero-etl", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Integraciones zero-ETL: cuando el pipeline desaparece" } },
  { id: "02-11-ingesta-por-lotes", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Ingesta por lotes: S3, Glue, EMR, Redshift COPY y Lambda" } },
  { id: "02-12-appflow-y-apis", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Amazon AppFlow, consumo de APIs de datos y allowlists de IP" } },
  { id: "02-13-throttling-y-limites", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Throttling, límites de tasa y reintentos (Kinesis, DynamoDB, RDS)" } },
  { id: "02-14-programadores-y-disparadores", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Programadores y disparadores: EventBridge Scheduler, S3 Event Notifications y Pipes" } },
  { id: "02-15-replayability-y-entrega", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Replayability y semántica de entrega: at-least-once, exactly-once e idempotencia" } },
  { id: "02-16-fan-out-y-transacciones", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Fan-in, fan-out y transacciones stateful frente a stateless" } },
  { id: "02-17-comparativas-ingesta", moduleId: "module-2", module: MODULES["module-2"], title: { es: "★ Tablas comparativas: Data Streams vs. Firehose vs. MSK vs. Flink vs. DMS vs. AppFlow" } },
  { id: "02-18-analisis-preguntas-modulo-2", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Analiza preguntas de examen: ingesta" }, kind: "quiz" },

  { id: "03-01-elegir-el-motor-de-transformacion", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Cómo se elige el motor de transformación: Glue, EMR, Lambda o Redshift" } },
  { id: "03-02-aws-glue-etl", moduleId: "module-3", module: MODULES["module-3"], title: { es: "AWS Glue ETL: jobs, DPU, tipos de worker y versiones" } },
  { id: "03-03-glue-dynamicframes-y-bookmarks", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Glue: DynamicFrames, job bookmarks y transformaciones habituales" } },
  { id: "03-04-glue-streaming-y-schema-registry", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Glue streaming ETL y AWS Glue Schema Registry" } },
  { id: "03-05-depurar-glue", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Depurar y optimizar jobs de Glue: fallos comunes y métricas" } },
  { id: "03-06-amazon-emr", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Amazon EMR: clústeres, tipos de nodo, EMRFS e instancias Spot" } },
  { id: "03-07-emr-serverless-y-eks", moduleId: "module-3", module: MODULES["module-3"], title: { es: "EMR Serverless y EMR on EKS" } },
  { id: "03-08-contenedores-para-datos", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Contenedores para procesamiento de datos: ECS, EKS, ECR y AWS Batch" } },
  { id: "03-09-conversion-de-formatos", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Transformar entre formatos: de CSV a Parquet y por qué importa" } },
  { id: "03-10-conectar-fuentes-jdbc-odbc", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Conectar fuentes heterogéneas: JDBC, ODBC y conexiones de Glue en VPC" } },
  { id: "03-11-integrar-varias-fuentes", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Integrar datos de varias fuentes: joins, deduplicación y datos que llegan tarde" } },
  { id: "03-12-optimizar-costos-de-procesamiento", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Optimizar el costo del procesamiento de datos" } },
  { id: "03-13-exponer-datos-como-api", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Exponer datos como API: API Gateway, Redshift Data API y Athena API" } },
  { id: "03-14-volumen-velocidad-variedad", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Volumen, velocidad y variedad: estructurados, semiestructurados y no estructurados" } },
  { id: "03-15-llms-para-procesar-datos", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Integrar LLMs en el procesamiento de datos: Amazon Bedrock" } },
  { id: "03-16-comparativas-transformacion", moduleId: "module-3", module: MODULES["module-3"], title: { es: "★ Tablas comparativas: motores de transformación" } },
  { id: "03-17-analisis-preguntas-modulo-3", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Analiza preguntas de examen: transformación" }, kind: "quiz" },

  { id: "04-01-step-functions", moduleId: "module-4", module: MODULES["module-4"], title: { es: "AWS Step Functions: máquinas de estado, Map, reintentos y manejo de errores" } },
  { id: "04-02-mwaa", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Amazon MWAA: Airflow gestionado, DAGs y cuándo conviene" } },
  { id: "04-03-glue-workflows-y-orquestacion-ligera", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Glue workflows y orquestación ligera con Lambda y EventBridge" } },
  { id: "04-04-pipelines-resilientes", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Pipelines resilientes: reintentos, DLQ, idempotencia y tolerancia a fallos" } },
  { id: "04-05-notificaciones-sns-y-sqs", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Notificaciones y alertas con Amazon SNS y Amazon SQS" } },
  { id: "04-06-lambda-para-datos", moduleId: "module-4", module: MODULES["module-4"], title: { es: "AWS Lambda para datos: memoria, timeout, concurrencia y almacenamiento" } },
  { id: "04-07-optimizar-codigo", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Optimizar código para reducir el tiempo de ejecución" } },
  { id: "04-08-lenguajes-y-frameworks", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Lenguajes y frameworks: Python, PySpark, SQL, Scala y scripting" } },
  { id: "04-09-estructuras-y-algoritmos", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Estructuras de datos y algoritmos que aparecen en el examen" } },
  { id: "04-10-buenas-practicas", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Buenas prácticas: control de versiones con Git, pruebas y logging" } },
  { id: "04-11-iac-para-datos", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Infraestructura como código: CloudFormation, CDK y SAM" } },
  { id: "04-12-ci-cd-de-pipelines", moduleId: "module-4", module: MODULES["module-4"], title: { es: "CI/CD de pipelines de datos: CodePipeline, CodeBuild y CodeDeploy" } },
  { id: "04-13-comparativas-orquestacion", moduleId: "module-4", module: MODULES["module-4"], title: { es: "★ Tablas comparativas: orquestadores y despliegue" } },
  { id: "04-14-analisis-preguntas-modulo-4", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Analiza preguntas de examen: orquestación y programación" }, kind: "quiz" },

  { id: "05-01-como-elegir-el-almacen", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Cómo elegir el almacén de datos: el árbol de decisión del examen" } },
  { id: "05-02-s3-como-data-lake", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Amazon S3 como data lake: clases, rendimiento, prefijos y Storage Lens" } },
  { id: "05-03-redshift-arquitectura", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Amazon Redshift: arquitectura, nodos, slices y RA3" } },
  { id: "05-04-redshift-serverless", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Redshift Serverless: RPU, escalado y cuándo conviene" } },
  { id: "05-05-redshift-distribucion-y-ordenamiento", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Redshift: distribution styles, sort keys y compresión" } },
  { id: "05-06-redshift-mantenimiento", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Redshift: WLM, concurrency scaling, VACUUM y ANALYZE" } },
  { id: "05-07-redshift-spectrum-y-federacion", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Redshift Spectrum, consultas federadas y vistas materializadas" } },
  { id: "05-08-bloqueos-y-concurrencia", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Bloqueos y concurrencia en Redshift y RDS" } },
  { id: "05-09-dynamodb", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Amazon DynamoDB: claves, índices LSI y GSI, capacidad y export a S3" } },
  { id: "05-10-rds-y-aurora", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Amazon RDS y Aurora en pipelines de datos" } },
  { id: "05-11-vectores-en-aurora", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Vectores en Aurora PostgreSQL: pgvector, HNSW e IVF" } },
  { id: "05-12-almacenes-especializados", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Almacenes especializados: MemoryDB, DocumentDB, Keyspaces y Neptune" } },
  { id: "05-13-opensearch-service", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Amazon OpenSearch Service: índices, ingestion pipelines y casos de uso" } },
  { id: "05-14-formatos-de-tabla-abiertos", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Formatos de tabla abiertos: Apache Iceberg, S3 Tables, Hudi y Delta Lake" } },
  { id: "05-15-almacenamiento-para-computo", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Almacenamiento para el cómputo: EBS, EFS e instance store" } },
  { id: "05-16-migracion-y-transferencia", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Migración y transferencia: Transfer Family, DataSync, Snow Family y los servicios de migración" } },
  { id: "05-17-comparativas-almacenes", moduleId: "module-5", module: MODULES["module-5"], title: { es: "★ Tablas comparativas: almacenes de datos uno junto a otro" } },
  { id: "05-18-analisis-preguntas-modulo-5", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Analiza preguntas de examen: almacenes de datos" }, kind: "quiz" },

  { id: "06-01-glue-data-catalog", moduleId: "module-6", module: MODULES["module-6"], title: { es: "AWS Glue Data Catalog y el Hive metastore" } },
  { id: "06-02-crawlers-de-glue", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Crawlers de Glue: descubrimiento de esquemas y clasificadores" } },
  { id: "06-03-particiones-en-el-catalogo", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Particiones en el catálogo: sincronización, MSCK REPAIR y partition projection" } },
  { id: "06-04-conexiones-para-catalogar", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Conexiones de origen y destino para catalogar" } },
  { id: "06-05-catalogos-de-negocio", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Catálogos de negocio: Amazon SageMaker Catalog y el glosario de datos" } },
  { id: "06-06-ciclo-de-vida-en-s3", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Ciclo de vida en S3: transiciones entre clases, Glacier y expiración" } },
  { id: "06-07-versionado-ttl-y-borrado", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Versionado de S3, TTL de DynamoDB y borrado por requisito legal" } },
  { id: "06-08-copy-y-unload", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Mover datos entre S3 y Redshift: COPY y UNLOAD" } },
  { id: "06-09-resiliencia-y-backup", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Resiliencia y disponibilidad: replicación, AWS Backup, PITR, RTO y RPO" } },
  { id: "06-10-modelado-para-redshift", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Modelado dimensional para Redshift: estrella, copo de nieve y tablas de hechos" } },
  { id: "06-11-modelado-para-dynamodb", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Modelado para DynamoDB: patrones de acceso primero y single-table design" } },
  { id: "06-12-modelado-del-data-lake", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Modelado sobre el data lake: zonas raw, curated y de consumo" } },
  { id: "06-13-evolucion-de-esquemas", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Evolución de esquemas y cambios en las características de los datos" } },
  { id: "06-14-conversion-de-esquemas", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Conversión de esquemas: AWS SCT y DMS Schema Conversion" } },
  { id: "06-15-linaje-de-datos", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Linaje de datos con herramientas de AWS" } },
  { id: "06-16-optimizacion-por-servicio", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Optimización por servicio: índices, particiones y compresión en S3, Redshift y DynamoDB" } },
  { id: "06-17-vectorizacion-y-bedrock", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Vectorización y knowledge bases de Amazon Bedrock" } },
  { id: "06-18-comparativas-catalogo-y-modelado", moduleId: "module-6", module: MODULES["module-6"], title: { es: "★ Tablas comparativas: catálogo, ciclo de vida y modelado" } },
  { id: "06-19-analisis-preguntas-modulo-6", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Analiza preguntas de examen: catálogo y modelado" }, kind: "quiz" },

  { id: "07-01-panorama-de-la-automatizacion", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Panorama de la automatización del procesamiento de datos" } },
  { id: "07-02-operar-step-functions-y-mwaa", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Operar Step Functions y MWAA: fallos, reintentos y diagnóstico" } },
  { id: "07-03-sdk-cli-y-apis-de-datos", moduleId: "module-7", module: MODULES["module-7"], title: { es: "SDK, AWS CLI y APIs de datos desde código" } },
  { id: "07-04-athena-fundamentos", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Amazon Athena: motor, particiones y costo por consulta" } },
  { id: "07-05-athena-workgroups-y-ctas", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Athena: workgroups, CTAS, vistas, UNLOAD y control de costos" } },
  { id: "07-06-athena-federacion-y-notebooks", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Athena: consultas federadas y notebooks con Apache Spark" } },
  { id: "07-07-glue-databrew", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Preparar datos sin escribir código: AWS Glue DataBrew" } },
  { id: "07-08-unified-studio-y-data-wrangler", moduleId: "module-7", module: MODULES["module-7"], title: { es: "SageMaker Unified Studio y SageMaker Data Wrangler" } },
  { id: "07-09-lambda-y-eventbridge", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Lambda y EventBridge en operación: reglas, programaciones y Pipes" } },
  { id: "07-10-quicksight", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Visualización con Amazon QuickSight: SPICE, datasets y permisos" } },
  { id: "07-11-sql-analitico", moduleId: "module-7", module: MODULES["module-7"], title: { es: "SQL analítico en Redshift y Athena: vistas, CTE y funciones de ventana" } },
  { id: "07-12-agregacion-y-pivoteo", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Agregación, medias móviles, agrupación y pivoteo" } },
  { id: "07-13-verificar-y-limpiar-datos", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Verificar y limpiar datos antes de publicarlos" } },
  { id: "07-14-provisionado-vs-serverless", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Provisionado frente a serverless: el compromiso que más se pregunta" } },
  { id: "07-15-amazon-q-y-kendra", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Amazon Q y Amazon Kendra: asistencia y búsqueda sobre los datos" } },
  { id: "07-16-comparativas-analisis", moduleId: "module-7", module: MODULES["module-7"], title: { es: "★ Tablas comparativas: consulta, preparación y visualización" } },
  { id: "07-17-analisis-preguntas-modulo-7", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Analiza preguntas de examen: automatización y análisis" }, kind: "quiz" },

  { id: "08-01-cloudwatch-para-pipelines", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Amazon CloudWatch para pipelines: métricas, logs y alarmas" } },
  { id: "08-02-cloudtrail", moduleId: "module-8", module: MODULES["module-8"], title: { es: "AWS CloudTrail y el seguimiento de llamadas a la API" } },
  { id: "08-03-centralizar-logs", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Extraer y centralizar logs para auditoría" } },
  { id: "08-04-analizar-logs", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Analizar logs: CloudWatch Logs Insights, Athena, OpenSearch y EMR" } },
  { id: "08-05-rendimiento-glue-y-emr", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Diagnóstico de rendimiento en Glue y EMR" } },
  { id: "08-06-rendimiento-redshift-y-athena", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Diagnóstico de rendimiento en Redshift y Athena" } },
  { id: "08-07-observabilidad-y-grafana", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Observabilidad de punta a punta y Amazon Managed Grafana" } },
  { id: "08-08-controlar-el-gasto", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Controlar el gasto: Cost Explorer, AWS Budgets y cost allocation tags" } },
  { id: "08-09-glue-data-quality", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Calidad de datos con AWS Glue Data Quality y DQDL" } },
  { id: "08-10-reglas-de-calidad-y-perfilado", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Definir reglas de calidad y perfilar datos con DataBrew" } },
  { id: "08-11-consistencia-y-reconciliacion", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Consistencia de datos y reconciliación entre origen y destino" } },
  { id: "08-12-muestreo-y-skew", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Muestreo de datos y data skew: qué son y cómo se corrigen" } },
  { id: "08-13-comparativas-monitoreo", moduleId: "module-8", module: MODULES["module-8"], title: { es: "★ Tablas comparativas: monitoreo, logs y calidad" } },
  { id: "08-14-analisis-preguntas-modulo-8", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Analiza preguntas de examen: monitoreo y calidad" }, kind: "quiz" },

  { id: "09-01-iam-para-datos", moduleId: "module-9", module: MODULES["module-9"], title: { es: "IAM para ingeniería de datos: usuarios, grupos, roles y políticas" } },
  { id: "09-02-roles-de-servicio", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Roles de servicio y relaciones de confianza: cómo Glue, EMR y Redshift acceden a los datos" } },
  { id: "09-03-politicas-y-menor-privilegio", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Políticas IAM personalizadas y el principio de menor privilegio" } },
  { id: "09-04-politicas-de-recurso", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Políticas de recurso: bucket policies, S3 Access Points y acceso entre cuentas" } },
  { id: "09-05-red-y-acceso-privado", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Acceso privado a la red: security groups, VPC endpoints y PrivateLink" } },
  { id: "09-06-proteger-endpoints", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Proteger endpoints de datos: API Gateway, AWS WAF, Shield, CloudFront y Route 53" } },
  { id: "09-07-secrets-manager", moduleId: "module-9", module: MODULES["module-9"], title: { es: "AWS Secrets Manager y la rotación de credenciales" } },
  { id: "09-08-secrets-vs-parameter-store", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Secrets Manager frente a Systems Manager Parameter Store" } },
  { id: "09-09-permisos-en-redshift", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Permisos dentro de Amazon Redshift: usuarios, grupos y roles de base de datos" } },
  { id: "09-10-lake-formation", moduleId: "module-9", module: MODULES["module-9"], title: { es: "AWS Lake Formation: permisos de tabla, columna, fila y celda" } },
  { id: "09-11-rbac-tbac-abac", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Autorización basada en roles, en etiquetas y en atributos (RBAC, TBAC, ABAC)" } },
  { id: "09-12-gestionados-vs-no-gestionados", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Servicios gestionados frente a no gestionados y la responsabilidad compartida" } },
  { id: "09-13-unified-studio-domains", moduleId: "module-9", module: MODULES["module-9"], title: { es: "SageMaker Unified Studio: domains, domain units y projects" } },
  { id: "09-14-comparativas-identidad", moduleId: "module-9", module: MODULES["module-9"], title: { es: "★ Tablas comparativas: identidad, permisos y acceso" } },
  { id: "09-15-analisis-preguntas-modulo-9", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Analiza preguntas de examen: autenticación y autorización" }, kind: "quiz" },

  { id: "10-01-kms", moduleId: "module-10", module: MODULES["module-10"], title: { es: "AWS KMS: tipos de clave, políticas y envelope encryption" } },
  { id: "10-02-cifrado-en-reposo", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Cifrado en reposo servicio por servicio: S3, Redshift, DynamoDB, EMR y Glue" } },
  { id: "10-03-cifrado-en-transito-y-entre-cuentas", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Cifrado en tránsito y cifrado entre cuentas y regiones" } },
  { id: "10-04-enmascaramiento", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Enmascaramiento y anonimización: Redshift dynamic data masking y detección de PII en Glue" } },
  { id: "10-05-cloudtrail-para-auditoria", moduleId: "module-10", module: MODULES["module-10"], title: { es: "CloudTrail para auditoría: trails, data events y trails de organización" } },
  { id: "10-06-cloudtrail-lake", moduleId: "module-10", module: MODULES["module-10"], title: { es: "AWS CloudTrail Lake: consultas centralizadas de auditoría" } },
  { id: "10-07-logs-de-auditoria-a-escala", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Logs de auditoría a escala: CloudWatch Logs, Athena, OpenSearch y EMR" } },
  { id: "10-08-identificacion-de-pii", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Identificación de PII con Amazon Macie y Lake Formation" } },
  { id: "10-09-compartir-datos", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Compartir datos: Redshift data sharing y AWS Data Exchange" } },
  { id: "10-10-gobierno-y-patrones", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Patrones de compartición y marcos de gobierno de datos" } },
  { id: "10-11-gobierno-con-sagemaker-catalog", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Gobierno con SageMaker Catalog: proyectos y suscripciones a datos" } },
  { id: "10-12-residencia-y-soberania", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Residencia y soberanía: impedir réplicas a regiones no permitidas" } },
  { id: "10-13-aws-config", moduleId: "module-10", module: MODULES["module-10"], title: { es: "AWS Config y el seguimiento de cambios de configuración" } },
  { id: "10-14-well-architected-tool", moduleId: "module-10", module: MODULES["module-10"], title: { es: "AWS Well-Architected Tool y la lente de analítica de datos" } },
  { id: "10-15-comparativas-seguridad", moduleId: "module-10", module: MODULES["module-10"], title: { es: "★ Tablas comparativas: cifrado, auditoría y gobierno" } },
  { id: "10-16-analisis-preguntas-modulo-10", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Analiza preguntas de examen: cifrado y gobierno" }, kind: "quiz" },

  { id: "11-01-repaso-por-dominio", moduleId: "module-11", module: MODULES["module-11"], title: { es: "Repaso relámpago por dominio: los datos que más se preguntan" } },
  { id: "11-02-trampas-del-examen", moduleId: "module-11", module: MODULES["module-11"], title: { es: "Las trampas del DEA-C01: los errores de concepto que más puntos cuestan" } },
  { id: "11-03-guia-de-descarte", moduleId: "module-11", module: MODULES["module-11"], title: { es: "Los servicios que se confunden: guía de descarte rápido" } },
  { id: "11-04-simulacro-completo", moduleId: "module-11", module: MODULES["module-11"], title: { es: "Simulacro completo: 65 preguntas en 130 minutos" }, kind: "quiz" },
  { id: "11-05-estrategia-del-dia", moduleId: "module-11", module: MODULES["module-11"], title: { es: "Estrategia del día del examen, gestión del tiempo y qué hacer si no apruebas" } },
];

export const manifest: CourseManifest = {
  slug: COURSE_SLUG,
  title: COURSE_TITLE,
  lessons: LESSONS,
};
