import type { CourseManifest, LessonMeta, LocalizedText } from "../types";

/**
 * Generated from this course's `README.md`, which is the human-readable index.
 * When a lesson is added, renamed, or reordered, change it there first and keep
 * this file in sync — the app navigates by this list.
 *
 * Titles are Spanish-only for now: the lessons themselves ship in `.es.md` and
 * the app falls back to the default locale for the rest.
 */

const MODULES: Record<string, LocalizedText> = {
  "module-1": { es: "Módulo 1 — La nube, tu cuenta AWS y el control del gasto" },
  "module-2": { es: "Módulo 2 — Identidad y accesos: IAM" },
  "module-3": { es: "Módulo 3 — Fundamentos del desarrollo web" },
  "module-4": { es: "Módulo 4 — Frontend con React y TypeScript" },
  "module-5": { es: "Módulo 5 — Publicar en AWS: S3, CloudFront y dominios" },
  "module-6": { es: "Módulo 6 — Backend serverless: Lambda y API Gateway" },
  "module-7": { es: "Módulo 7 — Datos NoSQL con DynamoDB" },
  "module-8": { es: "Módulo 8 — Datos relacionales: SQL, RDS y Aurora" },
  "module-9": { es: "Módulo 9 — Redes en AWS: VPC" },
  "module-10": { es: "Módulo 10 — Autenticación con Cognito" },
  "module-11": { es: "Módulo 11 — Archivos y multimedia con S3" },
  "module-12": { es: "Módulo 12 — Servidores y contenedores: EC2, Docker, ECS" },
  "module-13": { es: "Módulo 13 — Infraestructura como código: CloudFormation, SAM y CDK" },
  "module-14": { es: "Módulo 14 — Despliegue automático: Git, CI/CD y GitHub Actions" },
  "module-15": { es: "Módulo 15 — Observabilidad: ver qué pasa en producción" },
  "module-16": { es: "Módulo 16 — Arquitecturas asíncronas: colas, eventos y flujos" },
  "module-17": { es: "Módulo 17 — Costos, seguridad y proyecto final" },
};

const LESSONS: LessonMeta[] = [
  { id: "01-01-que-es-la-nube", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Qué es la nube y qué problema resuelve de verdad" } },
  { id: "01-02-que-es-full-stack", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Qué significa \"full stack\" y qué vas a construir en este curso" } },
  { id: "01-03-como-cobra-aws", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Cómo cobra AWS: pago por uso, Always Free, créditos y pruebas" } },
  { id: "01-04-crear-cuenta-aws", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Crear tu cuenta AWS paso a paso, sin sustos con la tarjeta" } },
  { id: "01-05-proteger-cuenta-root-mfa", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Blindar la cuenta: MFA en el usuario root y por qué nunca se trabaja con root" } },
  { id: "01-06-presupuesto-y-alertas", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Presupuesto y alertas de gasto con AWS Budgets (paso obligatorio del curso)" } },
  { id: "01-07-regiones-y-zonas", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Regiones y zonas de disponibilidad: por qué la región cambia el precio" } },
  { id: "01-08-tour-por-la-consola", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Tour por la consola: buscador, favoritos, cambio de región y CloudShell" } },
  { id: "01-09-etiquetas-y-limpieza", moduleId: "module-1", module: MODULES["module-1"], title: { es: "Etiquetas, nombres y la regla de limpieza del curso" } },
  { id: "01-10-ejercicio-auditoria-de-cuenta", moduleId: "module-1", module: MODULES["module-1"], title: { es: "⭐ Ejercicio guiado: auditoría de seguridad y costos de una cuenta recién creada" } },
  { id: "01-11-ejercicio-estimar-factura", moduleId: "module-1", module: MODULES["module-1"], title: { es: "⭐ Ejercicio guiado: estimar la factura de una app real con AWS Pricing Calculator" } },

  { id: "02-01-por-que-importa-iam", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Por qué IAM es lo primero que revisa un profesional" } },
  { id: "02-02-usuarios-grupos-root", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Usuarios, grupos y root: quién es quién en tu cuenta" } },
  { id: "02-03-politicas-iam", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Políticas IAM: leer un JSON de permisos sin miedo" } },
  { id: "02-04-menor-privilegio", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Políticas administradas vs propias y el principio de menor privilegio" } },
  { id: "02-05-roles-iam", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Roles IAM: identidad prestada, el concepto que más cuesta y más se usa" } },
  { id: "02-06-servicios-que-asumen-roles", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Cómo un servicio asume un rol: el caso de una Lambda leyendo un bucket" } },
  { id: "02-07-identity-center", moduleId: "module-2", module: MODULES["module-2"], title: { es: "IAM Identity Center: por qué las empresas ya casi no crean usuarios IAM" } },
  { id: "02-08-credenciales-y-cli", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Credenciales, access keys y AWS CLI: cuándo sí y cuándo nunca" } },
  { id: "02-09-revision-de-accesos", moduleId: "module-2", module: MODULES["module-2"], title: { es: "Herramientas de revisión: Access Analyzer, credential report y política de contraseñas" } },
  { id: "02-10-ejercicio-onboarding-junior", moduleId: "module-2", module: MODULES["module-2"], title: { es: "⭐ Ejercicio guiado: onboarding de un desarrollador junior con permisos mínimos" } },
  { id: "02-11-ejercicio-rol-minimo", moduleId: "module-2", module: MODULES["module-2"], title: { es: "⭐ Ejercicio guiado: el rol que rompe menos — acceso de una app a un solo bucket, y demostrarlo" } },

  { id: "03-01-como-funciona-la-web", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Cómo funciona la web: cliente, servidor, pedido y respuesta" } },
  { id: "03-02-http-basico", moduleId: "module-3", module: MODULES["module-3"], title: { es: "HTTP en 20 minutos: métodos, rutas, códigos de estado y cabeceras" } },
  { id: "03-03-html-y-css", moduleId: "module-3", module: MODULES["module-3"], title: { es: "HTML y CSS: la estructura y la ropa de una página" } },
  { id: "03-04-javascript-esencial", moduleId: "module-3", module: MODULES["module-3"], title: { es: "JavaScript esencial: variables, funciones, arrays y objetos" } },
  { id: "03-05-javascript-asincrono", moduleId: "module-3", module: MODULES["module-3"], title: { es: "JavaScript asíncrono: promesas, async/await y fetch" } },
  { id: "03-06-typescript-sin-dolor", moduleId: "module-3", module: MODULES["module-3"], title: { es: "TypeScript sin dolor: tipos, interfaces y los bugs que te ahorra" } },
  { id: "03-07-node-y-npm", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Node.js y npm: ejecutar JavaScript fuera del navegador" } },
  { id: "03-08-json-y-apis-rest", moduleId: "module-3", module: MODULES["module-3"], title: { es: "JSON y APIs REST: cómo se diseñan los endpoints" } },
  { id: "03-09-git-y-github", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Git y GitHub: control de versiones mínimo viable" } },
  { id: "03-10-entorno-de-trabajo", moduleId: "module-3", module: MODULES["module-3"], title: { es: "Tu entorno de trabajo: VS Code, Node, AWS CLI y CloudShell como plan B" } },
  { id: "03-11-ejercicio-api-local", moduleId: "module-3", module: MODULES["module-3"], title: { es: "⭐ Ejercicio guiado: la primera API de \"Pedidos Doña Rosa\" corriendo en tu máquina" } },
  { id: "03-12-ejercicio-pagina-consume-api", moduleId: "module-3", module: MODULES["module-3"], title: { es: "⭐ Ejercicio guiado: una página que consume tu API y maneja bien los errores" } },

  { id: "04-01-por-que-react", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Por qué React: del HTML a mano a los componentes" } },
  { id: "04-02-primer-proyecto-vite", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Tu primer proyecto con Vite + React + TypeScript" } },
  { id: "04-03-componentes-y-props", moduleId: "module-4", module: MODULES["module-4"], title: { es: "JSX, componentes y props" } },
  { id: "04-04-estado-y-eventos", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Estado con useState y manejo de eventos" } },
  { id: "04-05-useeffect-y-datos", moduleId: "module-4", module: MODULES["module-4"], title: { es: "useEffect y datos remotos: traer información de una API" } },
  { id: "04-06-listas-y-formularios", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Listas, formularios y validación básica" } },
  { id: "04-07-estados-carga-error-vacio", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Cargando, error y vacío: los tres estados que separan a un junior de un profesional" } },
  { id: "04-08-rutas-y-estructura", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Rutas en el frontend y organización de carpetas" } },
  { id: "04-09-build-de-produccion", moduleId: "module-4", module: MODULES["module-4"], title: { es: "Variables de entorno, build de producción y qué es un sitio estático" } },
  { id: "04-10-ejercicio-panel-de-pedidos", moduleId: "module-4", module: MODULES["module-4"], title: { es: "⭐ Ejercicio guiado: panel de pedidos de Doña Rosa en React" } },
  { id: "04-11-ejercicio-listo-para-produccion", moduleId: "module-4", module: MODULES["module-4"], title: { es: "⭐ Ejercicio guiado: dejarlo listo para producción — build, errores y checklist de calidad" } },

  { id: "05-01-que-es-s3", moduleId: "module-5", module: MODULES["module-5"], title: { es: "S3 y los buckets: el depósito de cajas de internet" } },
  { id: "05-02-permisos-de-s3", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Subir archivos y permisos: por qué \"hacerlo público\" casi nunca es la respuesta" } },
  { id: "05-03-hosting-estatico-s3", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Hosting estático en S3: servir tu aplicación React" } },
  { id: "05-04-que-es-cloudfront", moduleId: "module-5", module: MODULES["module-5"], title: { es: "CloudFront: la CDN explicada con el ejemplo de las sucursales" } },
  { id: "05-05-origin-access-control", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Bucket privado + Origin Access Control: la forma correcta de publicar" } },
  { id: "05-06-https-con-acm", moduleId: "module-5", module: MODULES["module-5"], title: { es: "HTTPS gratis con AWS Certificate Manager" } },
  { id: "05-07-dominios-y-route53", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Dominios y DNS con Route 53: qué cuesta realmente" } },
  { id: "05-08-cache-e-invalidaciones", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Caché e invalidaciones: por qué \"subí el cambio y no se ve\"" } },
  { id: "05-09-costos-s3-cloudfront", moduleId: "module-5", module: MODULES["module-5"], title: { es: "Costos de S3 y CloudFront: qué es gratis, qué no y dónde se dispara" } },
  { id: "05-10-ejercicio-web-en-produccion", moduleId: "module-5", module: MODULES["module-5"], title: { es: "⭐ Ejercicio guiado: la web de Doña Rosa en producción con HTTPS" } },
  { id: "05-11-ejercicio-despliegue-reproducible", moduleId: "module-5", module: MODULES["module-5"], title: { es: "⭐ Ejercicio guiado: despliegue reproducible — script de subida, invalidación y vuelta atrás" } },

  { id: "06-01-que-es-serverless", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Qué es serverless y por qué cambia la cuenta de la luz" } },
  { id: "06-02-primera-lambda", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Tu primera función Lambda desde la consola" } },
  { id: "06-03-anatomia-de-una-lambda", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Anatomía de una Lambda: handler, event, context y respuesta" } },
  { id: "06-04-memoria-timeout-variables", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Memoria, timeout y variables de entorno: los tres botones que tocan el precio" } },
  { id: "06-05-rol-de-ejecucion", moduleId: "module-6", module: MODULES["module-6"], title: { es: "El rol de ejecución: qué puede tocar tu función" } },
  { id: "06-06-api-gateway", moduleId: "module-6", module: MODULES["module-6"], title: { es: "API Gateway: convertir tu función en una URL pública (HTTP API vs REST API)" } },
  { id: "06-07-rutas-y-parametros", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Rutas, métodos y parámetros: path, query y body" } },
  { id: "06-08-cors", moduleId: "module-6", module: MODULES["module-6"], title: { es: "CORS explicado de una vez por todas" } },
  { id: "06-09-logs-y-depuracion", moduleId: "module-6", module: MODULES["module-6"], title: { es: "Logs y depuración con CloudWatch: lo mínimo para no sufrir" } },
  { id: "06-10-ejercicio-api-serverless", moduleId: "module-6", module: MODULES["module-6"], title: { es: "⭐ Ejercicio guiado: la API de pedidos, ahora serverless (CRUD completo)" } },
  { id: "06-11-ejercicio-conectar-front-y-api", moduleId: "module-6", module: MODULES["module-6"], title: { es: "⭐ Ejercicio guiado: conectar el React del módulo 4 con la API real" } },

  { id: "07-01-sql-vs-nosql", moduleId: "module-7", module: MODULES["module-7"], title: { es: "SQL vs NoSQL en palabras simples: la carpeta y el fichero" } },
  { id: "07-02-tablas-items-y-claves", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Tablas, ítems y claves: partition key y sort key" } },
  { id: "07-03-crear-tabla-on-demand", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Crear tu primera tabla en modo On-Demand (y por qué On-Demand para aprender)" } },
  { id: "07-04-operaciones-basicas", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Operaciones básicas desde la consola: crear, leer, actualizar y borrar" } },
  { id: "07-05-query-vs-scan", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Query vs Scan: la diferencia que te ahorra dinero" } },
  { id: "07-06-modelado-de-claves", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Modelado simple: pensar las claves antes de crear la tabla" } },
  { id: "07-07-indices-gsi", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Índices secundarios (GSI) sin complicarse" } },
  { id: "07-08-dynamodb-desde-lambda", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Usar DynamoDB desde Lambda con el SDK v3" } },
  { id: "07-09-costos-y-ttl", moduleId: "module-7", module: MODULES["module-7"], title: { es: "Costos, TTL y límites del free tier de DynamoDB" } },
  { id: "07-10-ejercicio-persistir-pedidos", moduleId: "module-7", module: MODULES["module-7"], title: { es: "⭐ Ejercicio guiado: los pedidos ya no se pierden — persistir la API en DynamoDB" } },
  { id: "07-11-ejercicio-datos-por-cliente", moduleId: "module-7", module: MODULES["module-7"], title: { es: "⭐ Ejercicio guiado: varias panaderías en la misma tabla — datos separados por cliente" } },

  { id: "08-01-cuando-usar-sql", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Cuándo conviene una base relacional (y cuándo no)" } },
  { id: "08-02-sql-esencial", moduleId: "module-8", module: MODULES["module-8"], title: { es: "SQL esencial: SELECT, INSERT, UPDATE, DELETE" } },
  { id: "08-03-relaciones-y-joins", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Relaciones y JOIN con el ejemplo de la panadería" } },
  { id: "08-04-que-es-rds", moduleId: "module-8", module: MODULES["module-8"], title: { es: "RDS: qué administra AWS y qué sigue siendo tuyo" } },
  { id: "08-05-crear-rds-free-tier", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Crear una instancia RDS free tier sin gastar de más" } },
  { id: "08-06-conectarse-a-la-base", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Conectarte a la base: host, puerto, usuario y un cliente SQL" } },
  { id: "08-07-secretos-y-contrasenas", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Dónde van las contraseñas: Parameter Store vs Secrets Manager" } },
  { id: "08-08-backups-y-snapshots", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Backups, snapshots y restauración: dormir tranquilo" } },
  { id: "08-09-aurora-serverless", moduleId: "module-8", module: MODULES["module-8"], title: { es: "Aurora Serverless v2: qué es y por qué todavía no lo enciendes" } },
  { id: "08-10-ejercicio-inventario-rds", moduleId: "module-8", module: MODULES["module-8"], title: { es: "⭐ Ejercicio guiado: inventario y ventas de la panadería en RDS" } },
  { id: "08-11-ejercicio-snapshot-y-restaurar", moduleId: "module-8", module: MODULES["module-8"], title: { es: "⭐ Ejercicio guiado: apaga y ahorra — snapshot, borrar la instancia y restaurarla" } },

  { id: "09-01-que-es-una-vpc", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Qué es una red privada y por qué AWS te regala una" } },
  { id: "09-02-cidr-y-subredes", moduleId: "module-9", module: MODULES["module-9"], title: { es: "CIDR y subredes explicadas con el ejemplo del edificio" } },
  { id: "09-03-publica-vs-privada", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Subred pública vs privada, Internet Gateway y tablas de rutas" } },
  { id: "09-04-nat-gateway-y-alternativas", moduleId: "module-9", module: MODULES["module-9"], title: { es: "NAT Gateway: el servicio que más facturas sorpresa genera (y cómo evitarlo)" } },
  { id: "09-05-security-groups-vs-nacl", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Security Groups vs Network ACLs: el portero y el muro" } },
  { id: "09-06-rds-en-subred-privada", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Poner tu base de datos en subred privada" } },
  { id: "09-07-vpc-endpoints", moduleId: "module-9", module: MODULES["module-9"], title: { es: "VPC endpoints: hablar con S3 y DynamoDB sin salir a internet" } },
  { id: "09-08-checklist-de-red", moduleId: "module-9", module: MODULES["module-9"], title: { es: "\"No conecta\": checklist de diagnóstico de red" } },
  { id: "09-09-costos-de-red", moduleId: "module-9", module: MODULES["module-9"], title: { es: "Costos de red: transferencia de datos e IPs públicas" } },
  { id: "09-10-ejercicio-vpc-a-mano", moduleId: "module-9", module: MODULES["module-9"], title: { es: "⭐ Ejercicio guiado: red de dos pisos — VPC con subred pública y privada, hecha a mano" } },
  { id: "09-11-ejercicio-lambda-en-vpc", moduleId: "module-9", module: MODULES["module-9"], title: { es: "⭐ Ejercicio guiado: base de datos blindada — Lambda dentro de la VPC hablando con RDS privada" } },

  { id: "10-01-autenticacion-vs-autorizacion", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Autenticación vs autorización: el portero y las llaves" } },
  { id: "10-02-tokens-jwt", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Cómo funciona el login moderno: tokens JWT, sesión y refresco" } },
  { id: "10-03-cognito-user-pools", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Cognito User Pools: tu directorio de usuarios" } },
  { id: "10-04-registro-y-verificacion", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Registro, verificación por email y políticas de contraseña" } },
  { id: "10-05-hosted-ui-o-propia", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Hosted UI o pantalla propia: cuándo conviene cada una" } },
  { id: "10-06-login-en-react", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Integrar el login en tu aplicación React" } },
  { id: "10-07-proteger-la-api", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Proteger la API: autorizador de Cognito en API Gateway" } },
  { id: "10-08-usuario-en-la-lambda", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Leer al usuario dentro de la Lambda y aislar sus datos" } },
  { id: "10-09-login-social-y-mfa", moduleId: "module-10", module: MODULES["module-10"], title: { es: "Login con Google y MFA para tus usuarios" } },
  { id: "10-10-ejercicio-login-real", moduleId: "module-10", module: MODULES["module-10"], title: { es: "⭐ Ejercicio guiado: Doña Rosa con login real y rutas protegidas" } },
  { id: "10-11-ejercicio-aislamiento-de-datos", moduleId: "module-10", module: MODULES["module-10"], title: { es: "⭐ Ejercicio guiado: cada quien ve lo suyo — aislamiento de datos y pruebas de intrusión básicas" } },

  { id: "11-01-archivos-fuera-de-la-base", moduleId: "module-11", module: MODULES["module-11"], title: { es: "Por qué los archivos no van dentro de la base de datos" } },
  { id: "11-02-presigned-urls", moduleId: "module-11", module: MODULES["module-11"], title: { es: "Presigned URLs: subir desde el navegador sin exponer llaves" } },
  { id: "11-03-descargas-seguras", moduleId: "module-11", module: MODULES["module-11"], title: { es: "Descargas seguras y enlaces que caducan" } },
  { id: "11-04-organizar-objetos", moduleId: "module-11", module: MODULES["module-11"], title: { es: "Organizar objetos: prefijos, convenciones de nombres y carpetas que no existen" } },
  { id: "11-05-clases-y-ciclo-de-vida", moduleId: "module-11", module: MODULES["module-11"], title: { es: "Clases de almacenamiento y reglas de ciclo de vida: bajar costos solo" } },
  { id: "11-06-versionado-y-proteccion", moduleId: "module-11", module: MODULES["module-11"], title: { es: "Versionado, borrado accidental y bloqueo de acceso público" } },
  { id: "11-07-eventos-s3-lambda", moduleId: "module-11", module: MODULES["module-11"], title: { es: "Eventos de S3 hacia Lambda: procesar un archivo apenas llega" } },
  { id: "11-08-costos-de-s3", moduleId: "module-11", module: MODULES["module-11"], title: { es: "Costos reales de S3: almacenamiento, peticiones y salida de datos" } },
  { id: "11-09-ejercicio-fotos-de-productos", moduleId: "module-11", module: MODULES["module-11"], title: { es: "⭐ Ejercicio guiado: fotos de los productos — subida directa, validación y galería" } },
  { id: "11-10-ejercicio-miniaturas", moduleId: "module-11", module: MODULES["module-11"], title: { es: "⭐ Ejercicio guiado: fábrica de miniaturas — evento S3 → Lambda → thumbnail + ciclo de vida" } },

  { id: "12-01-cuando-no-usar-serverless", moduleId: "module-12", module: MODULES["module-12"], title: { es: "Cuándo serverless no alcanza: casos reales para servidores" } },
  { id: "12-02-primera-instancia-ec2", moduleId: "module-12", module: MODULES["module-12"], title: { es: "EC2 en 15 minutos: lanzar una instancia free tier" } },
  { id: "12-03-session-manager", moduleId: "module-12", module: MODULES["module-12"], title: { es: "Conectarte con Session Manager, sin llaves SSH ni puertos abiertos" } },
  { id: "12-04-que-es-docker", moduleId: "module-12", module: MODULES["module-12"], title: { es: "Qué es Docker y por qué mata el \"en mi máquina funciona\"" } },
  { id: "12-05-primer-dockerfile", moduleId: "module-12", module: MODULES["module-12"], title: { es: "Tu primer Dockerfile para una API Node + TypeScript" } },
  { id: "12-06-ecr", moduleId: "module-12", module: MODULES["module-12"], title: { es: "ECR: guardar tu imagen dentro de AWS" } },
  { id: "12-07-ecs-fargate", moduleId: "module-12", module: MODULES["module-12"], title: { es: "ECS Fargate: contenedores sin administrar servidores" } },
  { id: "12-08-app-runner-y-beanstalk", moduleId: "module-12", module: MODULES["module-12"], title: { es: "App Runner y Elastic Beanstalk: las opciones \"fáciles\" y su letra chica" } },
  { id: "12-09-balanceadores-y-autoscaling", moduleId: "module-12", module: MODULES["module-12"], title: { es: "Balanceadores de carga y auto scaling en palabras simples" } },
  { id: "12-10-ejercicio-api-en-fargate", moduleId: "module-12", module: MODULES["module-12"], title: { es: "⭐ Ejercicio guiado: la API en un contenedor — Docker + ECR + Fargate por una hora, y borrar" } },
  { id: "12-11-ejercicio-comparativa-de-costos", moduleId: "module-12", module: MODULES["module-12"], title: { es: "⭐ Ejercicio guiado: la misma API en Lambda, Fargate y EC2 — comparativa de costo con números" } },

  { id: "13-01-el-problema-del-clic-a-mano", moduleId: "module-13", module: MODULES["module-13"], title: { es: "El problema de hacer todo a mano (y por qué tu cuenta ya es un desorden)" } },
  { id: "13-02-cloudformation", moduleId: "module-13", module: MODULES["module-13"], title: { es: "CloudFormation: plantillas, stacks y cambios controlados" } },
  { id: "13-03-leer-yaml", moduleId: "module-13", module: MODULES["module-13"], title: { es: "Leer una plantilla YAML sin miedo" } },
  { id: "13-04-parametros-y-outputs", moduleId: "module-13", module: MODULES["module-13"], title: { es: "Parámetros, outputs y referencias entre recursos" } },
  { id: "13-05-aws-sam", moduleId: "module-13", module: MODULES["module-13"], title: { es: "AWS SAM: la versión corta para serverless" } },
  { id: "13-06-desplegar-con-sam", moduleId: "module-13", module: MODULES["module-13"], title: { es: "Probar y desplegar con SAM de forma repetible" } },
  { id: "13-07-cdk-con-typescript", moduleId: "module-13", module: MODULES["module-13"], title: { es: "AWS CDK con TypeScript: infraestructura en el lenguaje que ya sabes" } },
  { id: "13-08-entornos-dev-y-prod", moduleId: "module-13", module: MODULES["module-13"], title: { es: "Entornos dev y prod, nombres y etiquetas desde el código" } },
  { id: "13-09-destruir-el-stack", moduleId: "module-13", module: MODULES["module-13"], title: { es: "Borrar todo con un comando: la ventaja de costos de la IaC" } },
  { id: "13-10-ejercicio-api-con-sam", moduleId: "module-13", module: MODULES["module-13"], title: { es: "⭐ Ejercicio guiado: tu API como código — recrear módulos 6 y 7 con SAM" } },
  { id: "13-11-ejercicio-dos-entornos-cdk", moduleId: "module-13", module: MODULES["module-13"], title: { es: "⭐ Ejercicio guiado: dos entornos, un comando — CDK con dev y prod, y destrucción limpia" } },

  { id: "14-01-que-es-ci-cd", moduleId: "module-14", module: MODULES["module-14"], title: { es: "Qué es CI/CD y qué dolor resuelve" } },
  { id: "14-02-ramas-y-pull-requests", moduleId: "module-14", module: MODULES["module-14"], title: { es: "Ramas, pull requests y flujo de trabajo en equipo" } },
  { id: "14-03-tests-minimos", moduleId: "module-14", module: MODULES["module-14"], title: { es: "Los tests automáticos mínimos que sí valen la pena" } },
  { id: "14-04-primer-workflow", moduleId: "module-14", module: MODULES["module-14"], title: { es: "GitHub Actions: tu primer workflow" } },
  { id: "14-05-oidc-sin-claves", moduleId: "module-14", module: MODULES["module-14"], title: { es: "Conectar GitHub con AWS sin claves: OIDC y un rol" } },
  { id: "14-06-deploy-del-frontend", moduleId: "module-14", module: MODULES["module-14"], title: { es: "Despliegue automático del frontend a S3 + CloudFront" } },
  { id: "14-07-deploy-del-backend", moduleId: "module-14", module: MODULES["module-14"], title: { es: "Despliegue automático del backend con SAM o CDK" } },
  { id: "14-08-alternativas-aws", moduleId: "module-14", module: MODULES["module-14"], title: { es: "Las alternativas de AWS: CodePipeline, CodeBuild y Amplify Hosting" } },
  { id: "14-09-ejercicio-pipeline-completo", moduleId: "module-14", module: MODULES["module-14"], title: { es: "⭐ Ejercicio guiado: de un push a producción — pipeline completo de front y back" } },
  { id: "14-10-ejercicio-rollback", moduleId: "module-14", module: MODULES["module-14"], title: { es: "⭐ Ejercicio guiado: rollback sin pánico — desplegar algo roto, detectarlo y volver atrás" } },

  { id: "15-01-logs-metricas-trazas", moduleId: "module-15", module: MODULES["module-15"], title: { es: "Por qué \"en mi máquina funciona\" no basta: logs, métricas y trazas" } },
  { id: "15-02-logs-insights", moduleId: "module-15", module: MODULES["module-15"], title: { es: "CloudWatch Logs: encontrar el error en dos minutos con Logs Insights" } },
  { id: "15-03-metricas-y-dashboards", moduleId: "module-15", module: MODULES["module-15"], title: { es: "Métricas y dashboards que se entienden de un vistazo" } },
  { id: "15-04-alarmas", moduleId: "module-15", module: MODULES["module-15"], title: { es: "Alarmas que avisan antes que el cliente" } },
  { id: "15-05-x-ray", moduleId: "module-15", module: MODULES["module-15"], title: { es: "AWS X-Ray: ver a dónde se va el tiempo" } },
  { id: "15-06-errores-en-produccion", moduleId: "module-15", module: MODULES["module-15"], title: { es: "Los errores clásicos de producción y cómo se ven en los logs" } },
  { id: "15-07-retencion-de-logs", moduleId: "module-15", module: MODULES["module-15"], title: { es: "Retención de logs: la fuga de dinero más silenciosa de AWS" } },
  { id: "15-08-timeouts-y-reintentos", moduleId: "module-15", module: MODULES["module-15"], title: { es: "Timeouts, reintentos y health checks" } },
  { id: "15-09-ejercicio-guardia-de-produccion", moduleId: "module-15", module: MODULES["module-15"], title: { es: "⭐ Ejercicio guiado: guardia de producción — dashboard, alarma y aviso por email" } },
  { id: "15-10-ejercicio-caza-del-bug", moduleId: "module-15", module: MODULES["module-15"], title: { es: "⭐ Ejercicio guiado: caza del bug — provocar una falla real y diagnosticarla con logs y trazas" } },

  { id: "16-01-sincrono-vs-asincrono", moduleId: "module-16", module: MODULES["module-16"], title: { es: "Síncrono vs asíncrono: la fila del banco" } },
  { id: "16-02-colas-con-sqs", moduleId: "module-16", module: MODULES["module-16"], title: { es: "SQS: colas y por qué dejas de perder trabajo" } },
  { id: "16-03-reintentos-y-dlq", moduleId: "module-16", module: MODULES["module-16"], title: { es: "Reintentos y Dead Letter Queues: dónde van los mensajes que fallan" } },
  { id: "16-04-sns-y-fanout", moduleId: "module-16", module: MODULES["module-16"], title: { es: "SNS: avisarle a varios a la vez" } },
  { id: "16-05-eventbridge", moduleId: "module-16", module: MODULES["module-16"], title: { es: "EventBridge: eventos y tareas programadas (el cron de la nube)" } },
  { id: "16-06-step-functions", moduleId: "module-16", module: MODULES["module-16"], title: { es: "Step Functions: flujos de varios pasos sin código pegamento" } },
  { id: "16-07-idempotencia", moduleId: "module-16", module: MODULES["module-16"], title: { es: "Idempotencia: el concepto que evita cobrarle dos veces al cliente" } },
  { id: "16-08-costos-de-mensajeria", moduleId: "module-16", module: MODULES["module-16"], title: { es: "Costos de mensajería y límites del free tier" } },
  { id: "16-09-ejercicio-email-asincrono", moduleId: "module-16", module: MODULES["module-16"], title: { es: "⭐ Ejercicio guiado: confirmación por email sin hacer esperar al cliente (API → SQS → Lambda → SES)" } },
  { id: "16-10-ejercicio-reporte-nocturno", moduleId: "module-16", module: MODULES["module-16"], title: { es: "⭐ Ejercicio guiado: el reporte nocturno — EventBridge programado → Step Functions → informe en S3" } },

  { id: "17-01-repaso-de-la-arquitectura", moduleId: "module-17", module: MODULES["module-17"], title: { es: "Repaso: la arquitectura completa que ya sabes construir" } },
  { id: "17-02-optimizacion-de-costos", moduleId: "module-17", module: MODULES["module-17"], title: { es: "Optimización de costos: los diez ajustes que más ahorran" } },
  { id: "17-03-checklist-de-seguridad", moduleId: "module-17", module: MODULES["module-17"], title: { es: "Revisión de seguridad de tu aplicación: checklist profesional" } },
  { id: "17-04-well-architected-en-la-practica", moduleId: "module-17", module: MODULES["module-17"], title: { es: "Well-Architected en la práctica: aplicar los pilares a tu proyecto" } },
  { id: "17-05-rendimiento-y-cache", moduleId: "module-17", module: MODULES["module-17"], title: { es: "Rendimiento: caché, paginación y las consultas que salen caras" } },
  { id: "17-06-proyecto-para-el-portfolio", moduleId: "module-17", module: MODULES["module-17"], title: { es: "Tu proyecto como carta de presentación: README, demo y entrevista" } },
  { id: "17-07-que-sigue", moduleId: "module-17", module: MODULES["module-17"], title: { es: "Qué sigue: certificaciones y caminos (Developer Associate, Solutions Architect)" } },
  { id: "17-08-cerrar-la-cuenta", moduleId: "module-17", module: MODULES["module-17"], title: { es: "Cómo cerrar o vaciar tu cuenta AWS sin dejar cargos colgados" } },
  { id: "17-09-auditoria-final", moduleId: "module-17", module: MODULES["module-17"], title: { es: "Auditoría final: encontrar y borrar recursos huérfanos" } },
  { id: "17-10-ejercicio-capstone-parte-1", moduleId: "module-17", module: MODULES["module-17"], title: { es: "⭐ Ejercicio guiado (capstone 1/2): el SaaS de pedidos — frontend, login, API y datos" } },
  { id: "17-11-ejercicio-capstone-parte-2", moduleId: "module-17", module: MODULES["module-17"], title: { es: "⭐ Ejercicio guiado (capstone 2/2): a producción — IaC, CI/CD, monitoreo y costo mensual estimado" } },
];

export const manifest: CourseManifest = {
  slug: "full-stack-developer-aws",
  title: { es: "Full Stack Developer con AWS" },
  lessons: LESSONS,
};
